name: ExploitsX
main: me.bait.exploitfixer.exploitfixer
version: 1.3.0azy
author: io.github.izdabait
description: Top of the line exploit fixer for large servers impacted by lag / crash exploits.
api-version: 1.16
commands:
  e:
    description: Basic ExploitsX command.
  exploits:
    description: Basic ExploitsX command.
  pl:
    description: ExploitsX pluginlist.
  stats:
    description: ExploitsX stats command.
    usage: /stats <playername>.
  stat:
    description: ExploitsX stats command.
    usage: /stat <playername>.
  statistics:
    description: ExploitsX stats command.
    usage: /statistics <playername>.
  togglechat:
    description: enables or disables chat for the player.
    usage: /toggleechat to disable or enable the chat.
  toggletells:
    description: enables or disables whispers for the player.
    usage: /toggletells to disable or enable whispers.
  ignore:
    description: allows a player to ignore or unignore another player.
    usage: /ignore <playername>.
  unignore:
    description: allows a player to ignore or unignore another player.
    usage: /unignore <playername>.
  ignorelist:
    description: Returns a list of all currently ignored players.
    usage: /ignorelist
  chatco:
    description: enables or disables whispers and spoilers.
    permission:
    usage: Only console input accepted. 'e' enables, 'd' disables. chatco whispers e/d, chatco spoilers e/d     
  xitem:
    description: spawn a shulker of items (for opped players only)
  uitem:
    description: spawn an unlimited item (for opped players only)
permissions:
  exploitsx.*:
    description: Admin ExploitsX permission
  exploitsx.snick:
    description: ExploitsX Nick
depend: [PlaceholderAPI]
